orbs:
  aws-s3: circleci/aws-s3@1.0.15

executors:
  node-executor:
    docker:
      - image: circleci/node:12.9.1-browsers
  python-executor:
    docker:
      - image: circleci/python:3.7

jobs:
  test-and-build:
    executor: node-executor 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run size
      - run: npm run coverage

      - run: npm build
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build 

  deploy-dev:
    executor: python-executor
    steps:
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          from: ~/project/build
          to: 's3://react-lab-dev-purposes/'
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true # default is false

  deploy-stage:
    executor: python-executor
    steps:
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          from: ~/project/build
          to: 's3://react-lab-staging-purposes/'
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true # default is false

  deploy-prod:
    executor: python-executor
    steps:
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          from: ~/project/build
          to: "s3://react-lab-purposes/"
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true # default is false

workflows:
  build-deploy-dev:
    filters:
      branches:
        only: develop
    jobs:
      - test-and-build:
          context: REACT_LAB

      - deploy-dev:
          context: REACT_LAB
          requires:
            - test-and-build

  build-deploy-stage:
    filters:
      branches:
        only: master
    jobs:
      - test-and-build:
          context: REACT_LAB_STAGE

      - deploy-stage:
          context: REACT_LAB_STAGE
          requires:
            - test-and-build
