version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
  cypress: cypress-io/cypress@1
executors:
  node-executor:
    docker:
      - image: circleci/node:12.9.1-browsers
  python-executor:
    docker:
      - image: circleci/python:3.7
jobs:
    executor: node-executor 
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run size
      - run: npm run coverage
      - run: npm build

      - persist_to_workspace:
          root: ~/
          paths:
            - project/build
          

  deploy-stage:
    executor: python-executor
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          from: bucket
          to: 's3://react-lab-staging-purposes/'
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true # default is false

  deploy-prod:
    executor: python-executor
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          from: bucket
          to: "s3://react-lab-purposes/"
          arguments: | # Optional arguments
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true # default is false

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-stage:
          context: REACT_LAB
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy-prod:
          context: REACT_LAB
          requires:
            - build
          filters:
            branches:
              only: master